{% set python_min = "3.10.0" %}
{% set name = "supabase-pydantic" %}
{% set version = "0.25.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/supabase_pydantic-{{ version }}.tar.gz
  sha256: e8cfb85873d3891b3731e5d32d5a78c580da5aa919e5c5e4b22db3cbd6812977

build:
  entry_points:
    - sb-pydantic = supabase_pydantic.cli:cli
    - supabase-pydantic = supabase_pydantic.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<3.14.0
    - psycopg2-binary >=2.9.9,<3.0.0
    - pydantic >=2.6.3,<3.0.0
    - types-psycopg2 >=2.9.21,<3.0.0
    - faker >=24.11.0,<25.0.0
    - python-dotenv >=1.0.1,<2.0.0
    - click >=8.1.7,<9.0.0
    - toml >=0.10.2,<0.11.0
    - click-option-group >=0.5.6,<0.6.0
    - inflection >=0.5.1,<0.6.0
    - requests >=2.32.4
    - urllib3 >=2.5.0,<3.0.0
    - loguru >=0.7.2,<0.8.0
    - mysql-connector-python >=8.0.32,<9.4.0
    - isort >=5.13.2,<6.0.0
    - jinja2 >=3.1.5,<3.2.0

test:
  imports:
    - supabase_pydantic
  commands:
    - pip check
    - sb-pydantic --help
    - supabase-pydantic --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/kmbhm1/supabase-pydantic
  summary: A Pydantic(+) model generator for Supabase
  license: MIT
  license_file: LICENSE
  doc_url: https://kmbhm1.github.io/supabase-pydantic
  dev_url: https://github.com/kmbhm1/supabase-pydantic

extra:
  recipe-maintainers:
    - kmbhm1
