{% set name = "supabase-pydantic" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/supabase_pydantic-{{ version }}.tar.gz
  sha256: e80e02c8b76bc6cb9ebf7c6b24958f80e4552975ee254b1677ebb07f3efdd1a2

build:
  entry_points:
    - sb-pydantic = supabase_pydantic.cli:cli
    - supabase-pydantic = supabase_pydantic.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.10.0,<4.0.0
    - psycopg2-binary >=2.9.9,<3.0.0
    - pydantic >=2.6.3,<3.0.0
    - types-psycopg2 >=2.9.21,<3.0.0
    - faker >=24.11.0,<25.0.0
    - isort >=5.13.2,<6.0.0
    - python-dotenv >=1.0.1,<2.0.0
    - click >=8.1.7,<9.0.0
    - toml >=0.10.2,<0.11.0
    - ruff >=0.4.1,<0.5.0
    - click-option-group >=0.5.6,<0.6.0

test:
  imports:
    - supabase_pydantic
  commands:
    - pip check
    - sb-pydantic --help
    - supabase-pydantic --help
  requires:
    - pip

about:
  home: https://github.com/kmbhm1/supabase-pydantic
  summary: A Pydantic(+) model generator for Supabase
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kmbhm1
